### ISSUE TITLE
Potential Issue with action prediction in `rvtpp_agent.py`

### ISSUE THREAD

**Issue by chan515x** [doublelei/VIHE#2]
Hi, @doublelei.

Thanks for your excellent work! 

 I was wondering in `rvtpp_agent.py`, it seems that the predicted action should be `continuous_action2` instead of `continuous_action` on line  [#L1118](https://github.com/doublelei/VIHE/blob/f2e0fa70a3c1a17d1759e6f813e4b70226e1381a/VIHE/models/rvtpp_agent.py#L1118)

Thanks for looking into this!

**Comment by doublelei** [comment]
Hi, you are right, continuous_action2 is the correct variable to use. Sorry for the mix-up when cleaning up the code. It's fixed now in [commit](https://github.com/doublelei/VIHE/commit/e9181fe9787cd932a333ba56857d3b036167dd5a)
